spring:
  datasource:
    #    url: jdbc:h2:tcp://localhost/~/test
    username: sa
    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        show_sql: false
        format_sql: false
        default_batch_fetch_size: 1000
        order_inserts: false
        order_updates: false
        query:
          in_clause_parameter_padding: true
    database: H2
  output:
    ansi:
      enabled: always
  h2:
    console:
      enabled: true
  redis:
    host: localhost
    port: 6379
